server:
  port: "8090"
spring:
  data:
    api:
      rootSzpUri: "http://0.0.0.0:8091"
      sendEventUri: "/api/generateFile"
  kafka:
    consumer:
      auto-offset-reset: latest
      auto-commit-interval: "10000"
    admin:
      properties:
        devTopic: "input_event_topic"
        devOutTopic: "output_event_topic"
        devFilePath: "/container/testDir"
        windMinDuration: "1"
    streams:
      application-id: "demo-app"
    bootstrap-servers: "http://kafkahost:9092"
